name: Trigger auto deployment for go-lang-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/go-lang-test-AutoDeployTrigger-e2d72d90-1b92-4e1d-a4d3-80b452d2db0f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GOLANGTEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GOLANGTEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GOLANGTEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/sampleWebApp
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.GOLANGTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GOLANGTEST_REGISTRY_PASSWORD }}
          containerAppName: go-lang-test
          resourceGroup: poc
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


